# examples of API-requests

@baseUrl = http://localhost:8081/api/v1

# product creation
POST {{baseUrl}}/products/
Content-Type: application/json

{
  "title": "Cucumber",
  "description": "The best cucumbers at the market"
}

###

# receipt of products
GET {{baseUrl}}/products/
Content-Type: application/json

###

# product update
PATCH {{baseUrl}}/products/2/
Content-Type: application/json

{
  "description": "The juiciest and most aromatic tomatoes"
}

###

# product removal
DELETE {{baseUrl}}/products/1/
Content-Type: application/json

###

# search for products by name and description
GET {{baseUrl}}/products/?search=рын
Content-Type: application/json

###

# stock creation
POST {{baseUrl}}/stocks/
Content-Type: application/json

{
  "address": "my address",
  "positions": [
    {
      "product": 2,
      "quantity": 250,
      "price": 120.50
    },
    {
      "product": 6,
      "quantity": 100,
      "price": 180
    }
  ]
}

###

# updating warehouse records
PATCH {{baseUrl}}/stocks/7/
Content-Type: application/json

{
  "positions": [
    {
      "product": 2,
      "quantity": 100,
      "price": 130.80
    },
    {
      "product": 6,
      "quantity": 243,
      "price": 145
    }
  ]
}

###

# searching for warehouses that stock a specific product
GET {{baseUrl}}/stocks/?products=2
Content-Type: application/json
